In [1]:
import numpy as np

In [2]:
sample1 = np.random.random((3, 2))    # 生成3行2列从0到1的随机数
sample1

array([[0.97691689, 0.06110165],
       [0.90651563, 0.66981195],
       [0.63594226, 0.60426492]])

In [3]:
sample2 = np.random.normal(size=(3, 2))    # 生成3行2列符合标准正态分布的随机数
sample2

array([[ 0.49900495, -0.58053495],
       [ 0.12179343, -0.58820433],
       [ 0.67321239,  1.89430778]])

In [4]:
sample3 = np.random.randint(0, 10, size=(3, 2))    # 生成3行2列从0到10的随机整数
sample3

array([[6, 6],
       [1, 0],
       [3, 9]])

In [5]:
np.sum(sample1)    # 矩阵求和

3.8545532937555866

In [6]:
np.min(sample1)    # 最小值

0.06110164738390378

In [7]:
np.max(sample1)    # 最大值

0.9769168858665588

In [8]:
np.sum(sample1, axis=0)    # axis=0 对列求和

array([2.51937477, 1.33517852])

In [9]:
np.argmin(sample1)    # 最小值的索引

1

In [10]:
np.argmax(sample1)    # 最大值的索引

0

In [11]:
np.mean(sample1)       # 求平均值  sample1.mean()

0.6424255489592644

In [12]:
np.median(sample1)     # 求中位数

0.6528771061863752

In [13]:
np.sqrt(sample1)        # 开方

array([[0.98839106, 0.24718747],
       [0.95211114, 0.8184204 ],
       [0.79745988, 0.77734479]])

In [14]:
sample4 = np.random.randint(0, 10, size=(1, 10))
sample4

array([[9, 6, 8, 7, 8, 1, 3, 8, 2, 1]])

In [15]:
np.sort(sample4)    # 排序

array([[1, 1, 2, 3, 6, 7, 8, 8, 8, 9]])

In [16]:
np.clip(sample4, 2, 7)     # 小于2的数变成2, 大于7的数变成7

array([[7, 6, 7, 7, 7, 2, 3, 7, 2, 2]])