In [1]:
import numpy as np

In [2]:
arr1 = np.arange(2, 14)
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [3]:
arr1[1:4]     # 半开半闭区间

array([3, 4, 5])

In [4]:
arr1[2:-1]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [6]:
arr2[1]

array([6, 7, 8, 9])

In [7]:
arr2[1][1]

7

In [9]:
arr2[1, 1]

7

In [10]:
arr2[:, 2]

array([ 4,  8, 12])

In [11]:
for i in arr2.flat:     # flat用于将多维数组转成一维数组
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
