In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.vstack((arr1, arr2))      # 垂直合并

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.hstack((arr1, arr2))      # 水平合并

array([1, 2, 3, 4, 5, 6])

In [5]:
np.concatenate((arr1, arr2, arr1))

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [11]:
arr1_1 = arr1[np.newaxis, :]
print(arr1_1)
arr1_1.shape

[[1 2 3]]


(1, 3)

In [12]:
arr1_1.T

array([[1],
       [2],
       [3]])

In [13]:
arr1_2 = arr1[:, np.newaxis]
print(arr1_2)
arr1_2.shape

[[1]
 [2]
 [3]]


(3, 1)

In [15]:
arr1_3 = np.atleast_2d(arr1)      # atleast_2d 最少是二维矩阵
print(arr1_3)
arr1_3.shape

[[1 2 3]]


(1, 3)

In [16]:
arr1_4 = np.atleast_3d(arr1)
print(arr1_4)
arr1_4.shape

[[[1]
  [2]
  [3]]]


(1, 3, 1)